# Site settings
title: Dufan Wu
general_email: wudufan33@gmail.com
academic_email: dwu6@mgh.harvard.edu

description: > # this means to ignore newlines until "baseurl:"
  Research fellow at MGH & HMS on CT imaging.

# baseurl: / # the subpath of your site, e.g. /blog/

# url: "https://wudufan.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: wudufan
linkedin_username: wudufan
# facebook_username: facebook_username
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title